### ISSUE TITLE
Error at startup

### ISSUE THREAD

**Issue by billbarni** [alan345/angular-socket#1]
I'm trying to follow step 3 and follow with the application startup, but there is no `config.js` in `/server/config` folder.

If I ignore it and just use `npm run start` the following error is presented:

```
module.js:529
    throw err;
    ^

Error: Cannot find module './config/config'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\William\Desktop\RealTime-Maps-and-Chat-with-
Angular-SocketIo\server\app.js:7:20)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\William\Desktop\RealTime-Maps-and-Chat-with-
Angular-SocketIo\bin\www.js:7:11)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
```

Can you help me overcome this issue? Thanks for sharing this code. It seems very good.

**Comment by alan345** [comment]
Hi, I have updated repo:
https://github.com/alan345/RealTime-Maps-and-Chat-with-Angular-SocketIo/commit/87baddfd580aff2d1d398d92330ae58323bae208
Please let me know if it helps.
